name: SecureAuth Pipeline

on:
  push:
    branches:
      - feature/**  

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t secureapp:latest .

      - name: Run Tests
        run: docker run  --rm -v $(pwd):/app secureapp:latest python manage.py test

  merge_to_main:
    needs: build_and_test  
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      pull-requests: write 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Merge to Main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ github.ref_name }}
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build_and_test_main:  
    needs: merge_to_main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image (Main)
        run: docker build -t secureapp:latest .

      - name: Run Tests (Main)
        run: docker run  --rm -v $(pwd):/app secureapp:latest python manage.py test

  
